# Google Cloud Build Configuration for Next.js 15 Application
# Service: jobcopilot
# Project: myresume-457817
# Region: us-west1
#
# This configuration builds a Docker image, pushes to Artifact Registry,
# and deploys to Cloud Run with Secret Manager integration.
#
# Usage: gcloud builds submit --config cloudbuild.yaml --substitutions=SHORT_SHA=$(git rev-parse --short HEAD)

steps:
  # Step 1: Build Docker image with build-time secrets from Secret Manager
  # These NEXT_PUBLIC_* variables are embedded in the client bundle
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$FIREBASE_WEB_API_KEY \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$FIREBASE_APP_ID \
          --build-arg NEXT_PUBLIC_SITE_URL=$$SITE_URL \
          --build-arg GEMINI_API_KEY=$$GEMINI_API_KEY_BUILD \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_SHORT_SHA} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest \
          .
    secretEnv:
      - 'FIREBASE_WEB_API_KEY'
      - 'FIREBASE_AUTH_DOMAIN'
      - 'FIREBASE_PROJECT_ID'
      - 'FIREBASE_STORAGE_BUCKET'
      - 'FIREBASE_MESSAGING_SENDER_ID'
      - 'FIREBASE_APP_ID'
      - 'SITE_URL'
      - 'GEMINI_API_KEY_BUILD'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}'

  # Step 3: Deploy to Cloud Run with runtime secrets from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # Resource configuration (required for Chromium/Puppeteer)
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--min-instances=0'
      # Environment variables (non-secret)
      - '--set-env-vars=NODE_ENV=production'
      # Runtime secrets from Secret Manager
      # Format: SECRET_NAME=SECRET_MANAGER_NAME:version
      - '--set-secrets=FIREBASE_SERVICE_ACCOUNT_KEY=ServiceAccountKey:latest'
      - '--set-secrets=SERPAPI_KEY=SERPAPI_KEY:latest'
      - '--set-secrets=OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest'
      - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--set-secrets=THE_COMPANIES_API_TOKEN=THE_COMPANIES_API_TOKEN:latest'
      - '--set-secrets=GITHUB_TOKEN=GITHUB_TOKEN:latest'
      - '--set-secrets=CRON_SECRET=CRON_SECRET:latest'
      - '--set-secrets=GMAIL_USER=GMAIL_USER:latest'
      - '--set-secrets=GMAIL_PASS=GMAIL_APP_PASSWORD:latest'
      - '--set-secrets=NOTIFY_TO=NOTIFY_TO:latest'
      - '--set-secrets=NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest'
      # Add NEXTAUTH_URL after first deployment - it needs the Cloud Run URL
      # After first deploy, add: --set-env-vars=NEXTAUTH_URL=https://YOUR-SERVICE-URL

# Timeout for entire build (30 minutes for initial builds with pnpm install)
timeout: 1800s

# Substitutions (default values, can be overridden)
substitutions:
  _SERVICE_NAME: 'jobcopilot'
  _REGION: 'us-west1'
  _SHORT_SHA: 'manual'  # Overridden by deploy.sh with git SHA

# Build-time secrets accessed from Secret Manager
# These are used as --build-arg in the Docker build step
availableSecrets:
  secretManager:
    # Firebase client configuration (public, embedded in bundle)
    - versionName: projects/${PROJECT_ID}/secrets/FIREBASE_WEB_API_KEY/versions/latest
      env: 'FIREBASE_WEB_API_KEY'
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'FIREBASE_AUTH_DOMAIN'
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'FIREBASE_PROJECT_ID'
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'FIREBASE_STORAGE_BUCKET'
    - versionName: projects/${PROJECT_ID}/secrets/FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/${PROJECT_ID}/secrets/FIREBASE_APP_ID/versions/latest
      env: 'FIREBASE_APP_ID'
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_SITE_URL/versions/latest
      env: 'SITE_URL'
    # GEMINI_API_KEY for Next.js build (prevents build failure during page data collection)
    - versionName: projects/${PROJECT_ID}/secrets/GEMINI_API_KEY/versions/latest
      env: 'GEMINI_API_KEY_BUILD'

# Build options
options:
  # Use high-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Enable Docker layer caching for faster rebuilds
  substitutionOption: 'ALLOW_LOOSE'
  # Logging configuration
  logging: CLOUD_LOGGING_ONLY

# Note: Before first deployment, ensure these secrets exist in Secret Manager:
# - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
# - NEXT_PUBLIC_FIREBASE_PROJECT_ID
# - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
# - NEXTAUTH_SECRET
# - NEXT_PUBLIC_SITE_URL
# - NOTIFY_TO (or use ADMIN_EMAIL)
#
# All other secrets already exist based on your Secret Manager list.
#
# To create missing secrets:
# echo -n "value" | gcloud secrets create SECRET_NAME --data-file=- --project=myresume-457817
#
# Grant Cloud Run service account access:
# gcloud secrets add-iam-policy-binding SECRET_NAME \
#   --member="serviceAccount:PROJECT_NUMBER-compute@developer.gserviceaccount.com" \
#   --role="roles/secretmanager.secretAccessor" \
#   --project=myresume-457817
